/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLogEntry {
  'id' : Principal,
  'action' : string,
  'createdAt' : Time,
  'actorId' : Principal,
  'updatedAt' : Time,
  'targetId' : Principal,
}
export interface EmploymentHistory {
  'startYear' : bigint,
  'endYear' : [] | [bigint],
  'role' : string,
  'employer' : string,
}
export interface JobApplication {
  'id' : Principal,
  'status' : string,
  'createdAt' : Time,
  'jobId' : Principal,
  'updatedAt' : Time,
  'teacherId' : Principal,
}
export interface JobListing {
  'id' : Principal,
  'region' : string,
  'schoolType' : string,
  'status' : string,
  'title' : string,
  'country' : string,
  'createdAt' : Time,
  'subjectsNeeded' : Array<string>,
  'updatedAt' : Time,
  'schoolId' : Principal,
  'roleOverview' : string,
  'gradesNeeded' : Array<string>,
}
export interface JobRequest {
  'id' : Principal,
  'status' : string,
  'clientId' : Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'requirements' : string,
}
export interface PersonalInfo {
  'country' : string,
  'name' : string,
  'nationality' : string,
  'email' : string,
  'phone' : string,
}
export interface RecruitmentPipelineEntry {
  'id' : string,
  'createdAt' : Time,
  'jobId' : Principal,
  'updatedAt' : Time,
  'stage' : string,
  'candidateId' : Principal,
}
export interface SavedJobs { 'jobId' : Principal, 'teacherId' : Principal }
export interface SchoolProfile {
  'id' : Principal,
  'schoolType' : string,
  'country' : string,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'contactEmail' : string,
}
export interface TalentPool {
  'id' : Principal,
  'filters' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
}
export interface TeacherDocument {
  'fileName' : string,
  'blobId' : string,
  'docType' : string,
  'uploadedAt' : Time,
}
export interface TeacherProfile {
  'id' : Principal,
  'grades' : Array<string>,
  'country' : string,
  'subjects' : Array<string>,
  'yearsExperience' : bigint,
  'name' : string,
  'createdAt' : Time,
  'qualifications' : Array<string>,
  'workPermitStatus' : string,
  'teachingDocuments' : Array<TeacherDocument>,
  'nationality' : string,
  'email' : string,
  'employmentType' : string,
  'updatedAt' : Time,
  'verifiedDocuments' : Array<string>,
  'employmentHistory' : Array<EmploymentHistory>,
  'phone' : string,
  'certifications' : Array<string>,
  'availabilityStatus' : string,
  'profileVisible' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToRecruitmentPipeline' : ActorMethod<
    [Principal, Principal, string],
    string
  >,
  'applyForJob' : ActorMethod<[Principal, Principal], Principal>,
  'approveSchool' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJobListing' : ActorMethod<
    [string, string, string, string, string, Principal],
    Principal
  >,
  'createJobRequest' : ActorMethod<[Principal, string], Principal>,
  'createSchoolProfile' : ActorMethod<
    [string, string, string, string],
    Principal
  >,
  'createTalentPool' : ActorMethod<[string, string, string], Principal>,
  'createTeacherProfile' : ActorMethod<[PersonalInfo], Principal>,
  'getActivityLogs' : ActorMethod<[], Array<ActivityLogEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobApplication' : ActorMethod<[Principal], [] | [JobApplication]>,
  'getJobApplications' : ActorMethod<[], Array<JobApplication>>,
  'getJobListing' : ActorMethod<[Principal], [] | [JobListing]>,
  'getJobListings' : ActorMethod<[], Array<JobListing>>,
  'getJobRequests' : ActorMethod<[], Array<JobRequest>>,
  'getRecruitmentPipelines' : ActorMethod<[], Array<RecruitmentPipelineEntry>>,
  'getSavedJobs' : ActorMethod<[], Array<SavedJobs>>,
  'getSavedJobsForTeacher' : ActorMethod<[Principal], Array<SavedJobs>>,
  'getSchoolProfile' : ActorMethod<[Principal], [] | [SchoolProfile]>,
  'getSchoolProfiles' : ActorMethod<[], Array<SchoolProfile>>,
  'getTalentPool' : ActorMethod<[Principal], [] | [TalentPool]>,
  'getTalentPools' : ActorMethod<[], Array<TalentPool>>,
  'getTeacherProfile' : ActorMethod<[Principal], [] | [TeacherProfile]>,
  'getTeacherProfiles' : ActorMethod<[], Array<TeacherProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logActivity' : ActorMethod<[Principal, string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveJob' : ActorMethod<[Principal, Principal], undefined>,
  'system_clearPersistentData' : ActorMethod<[], undefined>,
  'system_totalPersistentDataEntries' : ActorMethod<[], bigint>,
  'updateApplicationStatus' : ActorMethod<[Principal, string], undefined>,
  'updateJobListing' : ActorMethod<[Principal, JobListing], undefined>,
  'updateJobRequestStatus' : ActorMethod<[Principal, string], undefined>,
  'updatePipelineStage' : ActorMethod<[string, string], undefined>,
  'updateTeacherProfile' : ActorMethod<[TeacherProfile], undefined>,
  'verifyTeacherDocument' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];