/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PersonalInfo = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'nationality' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const ActivityLogEntry = IDL.Record({
  'id' : IDL.Principal,
  'action' : IDL.Text,
  'createdAt' : Time,
  'actorId' : IDL.Principal,
  'updatedAt' : Time,
  'targetId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const JobApplication = IDL.Record({
  'id' : IDL.Principal,
  'status' : IDL.Text,
  'createdAt' : Time,
  'jobId' : IDL.Principal,
  'updatedAt' : Time,
  'teacherId' : IDL.Principal,
});
export const JobListing = IDL.Record({
  'id' : IDL.Principal,
  'region' : IDL.Text,
  'schoolType' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'createdAt' : Time,
  'subjectsNeeded' : IDL.Vec(IDL.Text),
  'updatedAt' : Time,
  'schoolId' : IDL.Principal,
  'roleOverview' : IDL.Text,
  'gradesNeeded' : IDL.Vec(IDL.Text),
});
export const JobRequest = IDL.Record({
  'id' : IDL.Principal,
  'status' : IDL.Text,
  'clientId' : IDL.Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'requirements' : IDL.Text,
});
export const RecruitmentPipelineEntry = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'jobId' : IDL.Principal,
  'updatedAt' : Time,
  'stage' : IDL.Text,
  'candidateId' : IDL.Principal,
});
export const SavedJobs = IDL.Record({
  'jobId' : IDL.Principal,
  'teacherId' : IDL.Principal,
});
export const SchoolProfile = IDL.Record({
  'id' : IDL.Principal,
  'schoolType' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'contactEmail' : IDL.Text,
});
export const TalentPool = IDL.Record({
  'id' : IDL.Principal,
  'filters' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
});
export const TeacherDocument = IDL.Record({
  'fileName' : IDL.Text,
  'blobId' : IDL.Text,
  'docType' : IDL.Text,
  'uploadedAt' : Time,
});
export const EmploymentHistory = IDL.Record({
  'startYear' : IDL.Nat,
  'endYear' : IDL.Opt(IDL.Nat),
  'role' : IDL.Text,
  'employer' : IDL.Text,
});
export const TeacherProfile = IDL.Record({
  'id' : IDL.Principal,
  'grades' : IDL.Vec(IDL.Text),
  'country' : IDL.Text,
  'subjects' : IDL.Vec(IDL.Text),
  'yearsExperience' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'qualifications' : IDL.Vec(IDL.Text),
  'workPermitStatus' : IDL.Text,
  'teachingDocuments' : IDL.Vec(TeacherDocument),
  'nationality' : IDL.Text,
  'email' : IDL.Text,
  'employmentType' : IDL.Text,
  'updatedAt' : Time,
  'verifiedDocuments' : IDL.Vec(IDL.Text),
  'employmentHistory' : IDL.Vec(EmploymentHistory),
  'phone' : IDL.Text,
  'certifications' : IDL.Vec(IDL.Text),
  'availabilityStatus' : IDL.Text,
  'profileVisible' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToRecruitmentPipeline' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Text],
      [IDL.Text],
      [],
    ),
  'applyForJob' : IDL.Func([IDL.Principal, IDL.Principal], [IDL.Principal], []),
  'approveSchool' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJobListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Principal],
      [IDL.Principal],
      [],
    ),
  'createJobRequest' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Principal], []),
  'createSchoolProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Principal],
      [],
    ),
  'createTalentPool' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Principal],
      [],
    ),
  'createTeacherProfile' : IDL.Func([PersonalInfo], [IDL.Principal], []),
  'getActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLogEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobApplication' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(JobApplication)],
      ['query'],
    ),
  'getJobApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getJobListing' : IDL.Func([IDL.Principal], [IDL.Opt(JobListing)], ['query']),
  'getJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getJobRequests' : IDL.Func([], [IDL.Vec(JobRequest)], ['query']),
  'getRecruitmentPipelines' : IDL.Func(
      [],
      [IDL.Vec(RecruitmentPipelineEntry)],
      ['query'],
    ),
  'getSavedJobs' : IDL.Func([], [IDL.Vec(SavedJobs)], ['query']),
  'getSavedJobsForTeacher' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SavedJobs)],
      ['query'],
    ),
  'getSchoolProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SchoolProfile)],
      ['query'],
    ),
  'getSchoolProfiles' : IDL.Func([], [IDL.Vec(SchoolProfile)], ['query']),
  'getTalentPool' : IDL.Func([IDL.Principal], [IDL.Opt(TalentPool)], ['query']),
  'getTalentPools' : IDL.Func([], [IDL.Vec(TalentPool)], ['query']),
  'getTeacherProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TeacherProfile)],
      ['query'],
    ),
  'getTeacherProfiles' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logActivity' : IDL.Func([IDL.Principal, IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveJob' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'system_clearPersistentData' : IDL.Func([], [], []),
  'system_totalPersistentDataEntries' : IDL.Func([], [IDL.Nat], ['query']),
  'updateApplicationStatus' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateJobListing' : IDL.Func([IDL.Principal, JobListing], [], []),
  'updateJobRequestStatus' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updatePipelineStage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTeacherProfile' : IDL.Func([TeacherProfile], [], []),
  'verifyTeacherDocument' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PersonalInfo = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'nationality' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const ActivityLogEntry = IDL.Record({
    'id' : IDL.Principal,
    'action' : IDL.Text,
    'createdAt' : Time,
    'actorId' : IDL.Principal,
    'updatedAt' : Time,
    'targetId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const JobApplication = IDL.Record({
    'id' : IDL.Principal,
    'status' : IDL.Text,
    'createdAt' : Time,
    'jobId' : IDL.Principal,
    'updatedAt' : Time,
    'teacherId' : IDL.Principal,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Principal,
    'region' : IDL.Text,
    'schoolType' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'createdAt' : Time,
    'subjectsNeeded' : IDL.Vec(IDL.Text),
    'updatedAt' : Time,
    'schoolId' : IDL.Principal,
    'roleOverview' : IDL.Text,
    'gradesNeeded' : IDL.Vec(IDL.Text),
  });
  const JobRequest = IDL.Record({
    'id' : IDL.Principal,
    'status' : IDL.Text,
    'clientId' : IDL.Principal,
    'createdAt' : Time,
    'updatedAt' : Time,
    'requirements' : IDL.Text,
  });
  const RecruitmentPipelineEntry = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'jobId' : IDL.Principal,
    'updatedAt' : Time,
    'stage' : IDL.Text,
    'candidateId' : IDL.Principal,
  });
  const SavedJobs = IDL.Record({
    'jobId' : IDL.Principal,
    'teacherId' : IDL.Principal,
  });
  const SchoolProfile = IDL.Record({
    'id' : IDL.Principal,
    'schoolType' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'contactEmail' : IDL.Text,
  });
  const TalentPool = IDL.Record({
    'id' : IDL.Principal,
    'filters' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
  });
  const TeacherDocument = IDL.Record({
    'fileName' : IDL.Text,
    'blobId' : IDL.Text,
    'docType' : IDL.Text,
    'uploadedAt' : Time,
  });
  const EmploymentHistory = IDL.Record({
    'startYear' : IDL.Nat,
    'endYear' : IDL.Opt(IDL.Nat),
    'role' : IDL.Text,
    'employer' : IDL.Text,
  });
  const TeacherProfile = IDL.Record({
    'id' : IDL.Principal,
    'grades' : IDL.Vec(IDL.Text),
    'country' : IDL.Text,
    'subjects' : IDL.Vec(IDL.Text),
    'yearsExperience' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'qualifications' : IDL.Vec(IDL.Text),
    'workPermitStatus' : IDL.Text,
    'teachingDocuments' : IDL.Vec(TeacherDocument),
    'nationality' : IDL.Text,
    'email' : IDL.Text,
    'employmentType' : IDL.Text,
    'updatedAt' : Time,
    'verifiedDocuments' : IDL.Vec(IDL.Text),
    'employmentHistory' : IDL.Vec(EmploymentHistory),
    'phone' : IDL.Text,
    'certifications' : IDL.Vec(IDL.Text),
    'availabilityStatus' : IDL.Text,
    'profileVisible' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToRecruitmentPipeline' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Text],
        [IDL.Text],
        [],
      ),
    'applyForJob' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Principal],
        [],
      ),
    'approveSchool' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJobListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Principal],
        [IDL.Principal],
        [],
      ),
    'createJobRequest' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Principal],
        [],
      ),
    'createSchoolProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Principal],
        [],
      ),
    'createTalentPool' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Principal],
        [],
      ),
    'createTeacherProfile' : IDL.Func([PersonalInfo], [IDL.Principal], []),
    'getActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLogEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobApplication' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(JobApplication)],
        ['query'],
      ),
    'getJobApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getJobListing' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(JobListing)],
        ['query'],
      ),
    'getJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getJobRequests' : IDL.Func([], [IDL.Vec(JobRequest)], ['query']),
    'getRecruitmentPipelines' : IDL.Func(
        [],
        [IDL.Vec(RecruitmentPipelineEntry)],
        ['query'],
      ),
    'getSavedJobs' : IDL.Func([], [IDL.Vec(SavedJobs)], ['query']),
    'getSavedJobsForTeacher' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SavedJobs)],
        ['query'],
      ),
    'getSchoolProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SchoolProfile)],
        ['query'],
      ),
    'getSchoolProfiles' : IDL.Func([], [IDL.Vec(SchoolProfile)], ['query']),
    'getTalentPool' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TalentPool)],
        ['query'],
      ),
    'getTalentPools' : IDL.Func([], [IDL.Vec(TalentPool)], ['query']),
    'getTeacherProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TeacherProfile)],
        ['query'],
      ),
    'getTeacherProfiles' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logActivity' : IDL.Func([IDL.Principal, IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveJob' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
    'system_clearPersistentData' : IDL.Func([], [], []),
    'system_totalPersistentDataEntries' : IDL.Func([], [IDL.Nat], ['query']),
    'updateApplicationStatus' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateJobListing' : IDL.Func([IDL.Principal, JobListing], [], []),
    'updateJobRequestStatus' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updatePipelineStage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTeacherProfile' : IDL.Func([TeacherProfile], [], []),
    'verifyTeacherDocument' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };