/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TalentPool {
    id: Principal;
    filters: string;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
}
export interface PersonalInfo {
    country: string;
    name: string;
    nationality: string;
    email: string;
    phone: string;
}
export interface JobListing {
    id: Principal;
    region: string;
    schoolType: string;
    status: string;
    title: string;
    country: string;
    createdAt: Time;
    subjectsNeeded: Array<string>;
    updatedAt: Time;
    schoolId: Principal;
    roleOverview: string;
    gradesNeeded: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface JobApplication {
    id: Principal;
    status: string;
    createdAt: Time;
    jobId: Principal;
    updatedAt: Time;
    teacherId: Principal;
}
export interface ActivityLogEntry {
    id: Principal;
    action: string;
    createdAt: Time;
    actorId: Principal;
    updatedAt: Time;
    targetId: Principal;
}
export interface TeacherProfile {
    id: Principal;
    grades: Array<string>;
    country: string;
    subjects: Array<string>;
    yearsExperience: bigint;
    name: string;
    createdAt: Time;
    qualifications: Array<string>;
    workPermitStatus: string;
    teachingDocuments: Array<TeacherDocument>;
    nationality: string;
    email: string;
    employmentType: string;
    updatedAt: Time;
    verifiedDocuments: Array<string>;
    employmentHistory: Array<EmploymentHistory>;
    phone: string;
    certifications: Array<string>;
    availabilityStatus: string;
    profileVisible: boolean;
}
export interface EmploymentHistory {
    startYear: bigint;
    endYear?: bigint;
    role: string;
    employer: string;
}
export interface JobRequest {
    id: Principal;
    status: string;
    clientId: Principal;
    createdAt: Time;
    updatedAt: Time;
    requirements: string;
}
export interface RecruitmentPipelineEntry {
    id: string;
    createdAt: Time;
    jobId: Principal;
    updatedAt: Time;
    stage: string;
    candidateId: Principal;
}
export interface TeacherDocument {
    fileName: string;
    blobId: string;
    docType: string;
    uploadedAt: Time;
}
export interface SchoolProfile {
    id: Principal;
    schoolType: string;
    country: string;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    contactEmail: string;
}
export interface SavedJobs {
    jobId: Principal;
    teacherId: Principal;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addToRecruitmentPipeline(candidateId: Principal, jobId: Principal, stage: string): Promise<string>;
    applyForJob(teacherId: Principal, jobId: Principal): Promise<Principal>;
    approveSchool(schoolId: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createJobListing(title: string, region: string, country: string, schoolType: string, roleOverview: string, schoolId: Principal): Promise<Principal>;
    createJobRequest(clientId: Principal, requirements: string): Promise<Principal>;
    createSchoolProfile(name: string, contactEmail: string, country: string, schoolType: string): Promise<Principal>;
    createTalentPool(name: string, description: string, filters: string): Promise<Principal>;
    createTeacherProfile(personalInfo: PersonalInfo): Promise<Principal>;
    getActivityLogs(): Promise<Array<ActivityLogEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobApplication(applicationId: Principal): Promise<JobApplication | null>;
    getJobApplications(): Promise<Array<JobApplication>>;
    getJobListing(jobId: Principal): Promise<JobListing | null>;
    getJobListings(): Promise<Array<JobListing>>;
    getJobRequests(): Promise<Array<JobRequest>>;
    getRecruitmentPipelines(): Promise<Array<RecruitmentPipelineEntry>>;
    getSavedJobs(): Promise<Array<SavedJobs>>;
    getSavedJobsForTeacher(teacherId: Principal): Promise<Array<SavedJobs>>;
    getSchoolProfile(schoolId: Principal): Promise<SchoolProfile | null>;
    getSchoolProfiles(): Promise<Array<SchoolProfile>>;
    getTalentPool(poolId: Principal): Promise<TalentPool | null>;
    getTalentPools(): Promise<Array<TalentPool>>;
    getTeacherProfile(teacherId: Principal): Promise<TeacherProfile | null>;
    getTeacherProfiles(): Promise<Array<TeacherProfile>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logActivity(actorId: Principal, action: string, targetId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveJob(teacherId: Principal, jobId: Principal): Promise<void>;
    system_clearPersistentData(): Promise<void>;
    system_totalPersistentDataEntries(): Promise<bigint>;
    updateApplicationStatus(applicationId: Principal, newStatus: string): Promise<void>;
    updateJobListing(jobId: Principal, updates: JobListing): Promise<void>;
    updateJobRequestStatus(requestId: Principal, newStatus: string): Promise<void>;
    updatePipelineStage(entryId: string, newStage: string): Promise<void>;
    updateTeacherProfile(updates: TeacherProfile): Promise<void>;
    verifyTeacherDocument(teacherId: Principal, docId: string): Promise<void>;
}
import type { EmploymentHistory as _EmploymentHistory, JobApplication as _JobApplication, JobListing as _JobListing, SchoolProfile as _SchoolProfile, TalentPool as _TalentPool, TeacherDocument as _TeacherDocument, TeacherProfile as _TeacherProfile, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addToRecruitmentPipeline(arg0: Principal, arg1: Principal, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addToRecruitmentPipeline(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToRecruitmentPipeline(arg0, arg1, arg2);
            return result;
        }
    }
    async applyForJob(arg0: Principal, arg1: Principal): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForJob(arg0, arg1);
            return result;
        }
    }
    async approveSchool(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSchool(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSchool(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createJobListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Principal): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobListing(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobListing(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createJobRequest(arg0: Principal, arg1: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobRequest(arg0, arg1);
            return result;
        }
    }
    async createSchoolProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createSchoolProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSchoolProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTalentPool(arg0: string, arg1: string, arg2: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createTalentPool(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTalentPool(arg0, arg1, arg2);
            return result;
        }
    }
    async createTeacherProfile(arg0: PersonalInfo): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacherProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacherProfile(arg0);
            return result;
        }
    }
    async getActivityLogs(): Promise<Array<ActivityLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobApplication(arg0: Principal): Promise<JobApplication | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobApplication(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobApplication(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobApplications();
            return result;
        }
    }
    async getJobListing(arg0: Principal): Promise<JobListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListing(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListing(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListings();
            return result;
        }
    }
    async getJobRequests(): Promise<Array<JobRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobRequests();
            return result;
        }
    }
    async getRecruitmentPipelines(): Promise<Array<RecruitmentPipelineEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecruitmentPipelines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecruitmentPipelines();
            return result;
        }
    }
    async getSavedJobs(): Promise<Array<SavedJobs>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedJobs();
            return result;
        }
    }
    async getSavedJobsForTeacher(arg0: Principal): Promise<Array<SavedJobs>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedJobsForTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedJobsForTeacher(arg0);
            return result;
        }
    }
    async getSchoolProfile(arg0: Principal): Promise<SchoolProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchoolProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchoolProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchoolProfiles(): Promise<Array<SchoolProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchoolProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchoolProfiles();
            return result;
        }
    }
    async getTalentPool(arg0: Principal): Promise<TalentPool | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTalentPool(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTalentPool(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTalentPools(): Promise<Array<TalentPool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTalentPools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTalentPools();
            return result;
        }
    }
    async getTeacherProfile(arg0: Principal): Promise<TeacherProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherProfiles(): Promise<Array<TeacherProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherProfiles();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherProfiles();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logActivity(arg0: Principal, arg1: string, arg2: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logActivity(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logActivity(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveJob(arg0: Principal, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJob(arg0, arg1);
            return result;
        }
    }
    async system_clearPersistentData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.system_clearPersistentData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.system_clearPersistentData();
            return result;
        }
    }
    async system_totalPersistentDataEntries(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.system_totalPersistentDataEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.system_totalPersistentDataEntries();
            return result;
        }
    }
    async updateApplicationStatus(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, arg1);
            return result;
        }
    }
    async updateJobListing(arg0: Principal, arg1: JobListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobListing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobListing(arg0, arg1);
            return result;
        }
    }
    async updateJobRequestStatus(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobRequestStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobRequestStatus(arg0, arg1);
            return result;
        }
    }
    async updatePipelineStage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePipelineStage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePipelineStage(arg0, arg1);
            return result;
        }
    }
    async updateTeacherProfile(arg0: TeacherProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacherProfile(to_candid_TeacherProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacherProfile(to_candid_TeacherProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyTeacherDocument(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyTeacherDocument(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyTeacherDocument(arg0, arg1);
            return result;
        }
    }
}
function from_candid_EmploymentHistory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentHistory): EmploymentHistory {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TeacherProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeacherProfile): TeacherProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobApplication]): JobApplication | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobListing]): JobListing | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SchoolProfile]): SchoolProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TalentPool]): TalentPool | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeacherProfile]): TeacherProfile | null {
    return value.length === 0 ? null : from_candid_TeacherProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    grades: Array<string>;
    country: string;
    subjects: Array<string>;
    yearsExperience: bigint;
    name: string;
    createdAt: _Time;
    qualifications: Array<string>;
    workPermitStatus: string;
    teachingDocuments: Array<_TeacherDocument>;
    nationality: string;
    email: string;
    employmentType: string;
    updatedAt: _Time;
    verifiedDocuments: Array<string>;
    employmentHistory: Array<_EmploymentHistory>;
    phone: string;
    certifications: Array<string>;
    availabilityStatus: string;
    profileVisible: boolean;
}): {
    id: Principal;
    grades: Array<string>;
    country: string;
    subjects: Array<string>;
    yearsExperience: bigint;
    name: string;
    createdAt: Time;
    qualifications: Array<string>;
    workPermitStatus: string;
    teachingDocuments: Array<TeacherDocument>;
    nationality: string;
    email: string;
    employmentType: string;
    updatedAt: Time;
    verifiedDocuments: Array<string>;
    employmentHistory: Array<EmploymentHistory>;
    phone: string;
    certifications: Array<string>;
    availabilityStatus: string;
    profileVisible: boolean;
} {
    return {
        id: value.id,
        grades: value.grades,
        country: value.country,
        subjects: value.subjects,
        yearsExperience: value.yearsExperience,
        name: value.name,
        createdAt: value.createdAt,
        qualifications: value.qualifications,
        workPermitStatus: value.workPermitStatus,
        teachingDocuments: value.teachingDocuments,
        nationality: value.nationality,
        email: value.email,
        employmentType: value.employmentType,
        updatedAt: value.updatedAt,
        verifiedDocuments: value.verifiedDocuments,
        employmentHistory: from_candid_vec_n20(_uploadFile, _downloadFile, value.employmentHistory),
        phone: value.phone,
        certifications: value.certifications,
        availabilityStatus: value.availabilityStatus,
        profileVisible: value.profileVisible
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startYear: bigint;
    endYear: [] | [bigint];
    role: string;
    employer: string;
}): {
    startYear: bigint;
    endYear?: bigint;
    role: string;
    employer: string;
} {
    return {
        startYear: value.startYear,
        endYear: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.endYear)),
        role: value.role,
        employer: value.employer
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmploymentHistory>): Array<EmploymentHistory> {
    return value.map((x)=>from_candid_EmploymentHistory_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeacherProfile>): Array<TeacherProfile> {
    return value.map((x)=>from_candid_TeacherProfile_n18(_uploadFile, _downloadFile, x));
}
function to_candid_EmploymentHistory_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentHistory): _EmploymentHistory {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_TeacherProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeacherProfile): _TeacherProfile {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    grades: Array<string>;
    country: string;
    subjects: Array<string>;
    yearsExperience: bigint;
    name: string;
    createdAt: Time;
    qualifications: Array<string>;
    workPermitStatus: string;
    teachingDocuments: Array<TeacherDocument>;
    nationality: string;
    email: string;
    employmentType: string;
    updatedAt: Time;
    verifiedDocuments: Array<string>;
    employmentHistory: Array<EmploymentHistory>;
    phone: string;
    certifications: Array<string>;
    availabilityStatus: string;
    profileVisible: boolean;
}): {
    id: Principal;
    grades: Array<string>;
    country: string;
    subjects: Array<string>;
    yearsExperience: bigint;
    name: string;
    createdAt: _Time;
    qualifications: Array<string>;
    workPermitStatus: string;
    teachingDocuments: Array<_TeacherDocument>;
    nationality: string;
    email: string;
    employmentType: string;
    updatedAt: _Time;
    verifiedDocuments: Array<string>;
    employmentHistory: Array<_EmploymentHistory>;
    phone: string;
    certifications: Array<string>;
    availabilityStatus: string;
    profileVisible: boolean;
} {
    return {
        id: value.id,
        grades: value.grades,
        country: value.country,
        subjects: value.subjects,
        yearsExperience: value.yearsExperience,
        name: value.name,
        createdAt: value.createdAt,
        qualifications: value.qualifications,
        workPermitStatus: value.workPermitStatus,
        teachingDocuments: value.teachingDocuments,
        nationality: value.nationality,
        email: value.email,
        employmentType: value.employmentType,
        updatedAt: value.updatedAt,
        verifiedDocuments: value.verifiedDocuments,
        employmentHistory: to_candid_vec_n26(_uploadFile, _downloadFile, value.employmentHistory),
        phone: value.phone,
        certifications: value.certifications,
        availabilityStatus: value.availabilityStatus,
        profileVisible: value.profileVisible
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startYear: bigint;
    endYear?: bigint;
    role: string;
    employer: string;
}): {
    startYear: bigint;
    endYear: [] | [bigint];
    role: string;
    employer: string;
} {
    return {
        startYear: value.startYear,
        endYear: value.endYear ? candid_some(value.endYear) : candid_none(),
        role: value.role,
        employer: value.employer
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EmploymentHistory>): Array<_EmploymentHistory> {
    return value.map((x)=>to_candid_EmploymentHistory_n27(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
